version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - config/.env.local
    depends_on:
      - supabase_db

  supabase_db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres.mufexywealhbqphmpmgq
      POSTGRES_PASSWORD: U7M9WEKYqauxENcm
